import copy


DEFAULT_BATCH_EVICTION_INTERVAL = "1m0s"
DEFAULT_BATCH_EVICTION_SIZE = 10
DEFAULT_WORKLOAD_UPDATE_METHODS = ["LiveMigrate", "Evict"]
DEFAULT_WORKLOAD_UPDATE_STRATEGY = {
    "batchEvictionInterval": DEFAULT_BATCH_EVICTION_INTERVAL,
    "batchEvictionSize": DEFAULT_BATCH_EVICTION_SIZE,
    "workloadUpdateMethods": DEFAULT_WORKLOAD_UPDATE_METHODS,
}

CUSTOM_BATCH_EVICTION_INTERVAL = "5m0s"
CUSTOM_BATCH_EVICTION_SIZE = 20
CUSTOM_WORKLOAD_UPDATE_METHODS = ["LiveMigrate"]
CUSTOM_WORKLOAD_UPDATE_STRATEGY = {
    "batchEvictionInterval": CUSTOM_BATCH_EVICTION_INTERVAL,
    "batchEvictionSize": CUSTOM_BATCH_EVICTION_SIZE,
    "workloadUpdateMethods": CUSTOM_WORKLOAD_UPDATE_METHODS,
}
MOD_DEFAULT_BATCH_EVICTION_INTERVAL = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_SIZE = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_WORKLOAD_UPDATE_STRATEGY = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_INTERVAL[
    "batchEvictionInterval"
] = CUSTOM_BATCH_EVICTION_INTERVAL
MOD_DEFAULT_BATCH_EVICTION_SIZE["batchEvictionSize"] = CUSTOM_BATCH_EVICTION_SIZE
MOD_DEFAULT_WORKLOAD_UPDATE_STRATEGY[
    "workloadUpdateMethods"
] = CUSTOM_WORKLOAD_UPDATE_METHODS
MOD_CUST_DEFAULT_BATCH_EVICTION_INTERVAL = copy.deepcopy(
    CUSTOM_WORKLOAD_UPDATE_STRATEGY
)
MOD_CUST_DEFAULT_BATCH_EVICTION_SIZE = copy.deepcopy(CUSTOM_WORKLOAD_UPDATE_STRATEGY)
MOD_CUST_DEFAULT_WORKLOAD_UPDATE_METHOD = copy.deepcopy(CUSTOM_WORKLOAD_UPDATE_STRATEGY)
MOD_CUST_DEFAULT_BATCH_EVICTION_INTERVAL[
    "batchEvictionInterval"
] = DEFAULT_BATCH_EVICTION_INTERVAL
MOD_CUST_DEFAULT_BATCH_EVICTION_SIZE["batchEvictionSize"] = DEFAULT_BATCH_EVICTION_SIZE
MOD_CUST_DEFAULT_WORKLOAD_UPDATE_METHOD[
    "workloadUpdateMethods"
] = DEFAULT_WORKLOAD_UPDATE_METHODS

CUSTOM_WORKLOAD_STRATEGY_SPEC = {
    "spec": {"workloadUpdateStrategy": CUSTOM_WORKLOAD_UPDATE_STRATEGY}
}
