import copy

from ocp_resources.cdi import CDI
from ocp_resources.configmap import ConfigMap
from ocp_resources.console_cli_download import ConsoleCLIDownload
from ocp_resources.console_quick_start import ConsoleQuickStart
from ocp_resources.kubevirt import KubeVirt
from ocp_resources.network_addons_config import NetworkAddonsConfig
from ocp_resources.priority_class import PriorityClass
from ocp_resources.prometheus_rule import PrometheusRule
from ocp_resources.resource import Resource
from ocp_resources.route import Route
from ocp_resources.service import Service
from ocp_resources.service_monitor import ServiceMonitor
from ocp_resources.ssp import SSP

from utilities.constants import (
    CDI_KUBEVIRT_HYPERCONVERGED,
    CDI_OPERATOR,
    CLUSTER_NETWORK_ADDONS_OPERATOR,
    HCO_OPERATOR,
    HCO_PART_OF_LABEL_VALUE,
    HCO_WEBHOOK,
    HOSTPATH_PROVISIONER_OPERATOR,
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD,
    MANAGED_BY_LABEL_VALUE_OLM,
    SSP_KUBEVIRT_HYPERCONVERGED,
    SSP_OPERATOR,
    VIRT_OPERATOR,
    VIRTCTL_CLI_DOWNLOADS,
)


CLUSTER_SCOPE_RESOURCES = [
    "CDI",
    "NetworkAddonsConfig",
    "VMImportConfig",
    "ConsoleCLIDownload",
    "PriorityClass",
    "ConsoleQuickStart",
]
# components
COMPONENT_LABEL_TEMPLATING_VALUE = "templating"
COMPONENT_LABEL_DEPLOYMENT_VALUE = "deployment"
COMPONENT_LABEL_MONITORING_VALUE = "monitoring"
COMPONENT_LABEL_SCHEDULE_VALUE = "schedule"
COMPONENT_LABEL_COMPUTE_VALUE = "compute"
COMPONENT_LABEL_IMPORT_VALUE = "import"
COMPONENT_LABEL_STORAGE_VALUE = "storage"
COMPONENT_LABEL_NETWORK_VALUE = "network"
# labels keys
MANAGED_BY_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/managed-by"
VERSION_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/version"
COMPONENT_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/component"
PART_OF_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/part-of"
ALL_LABEL_KEYS = [
    MANAGED_BY_LABEL_KEY,
    VERSION_LABEL_KEY,
    COMPONENT_LABEL_KEY,
    PART_OF_LABEL_KEY,
]
# labels values
HCO_MANAGED_BY_LABEL_VALUE = HCO_OPERATOR
# HCO
HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE = {
    MANAGED_BY_LABEL_KEY: HCO_MANAGED_BY_LABEL_VALUE,
    VERSION_LABEL_KEY: None,
    COMPONENT_LABEL_KEY: None,
    PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
}
EXPECTED_TEMPLATING_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_TEMPLATING_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_TEMPLATING_VALUE
EXPECTED_SCHEDULE_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_SCHEDULE_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_SCHEDULE_VALUE
EXPECTED_MONITORING_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_MONITORING_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_MONITORING_VALUE
EXPECTED_NETWORK_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_NETWORK_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_NETWORK_VALUE
EXPECTED_IMPORT_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_IMPORT_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_IMPORT_VALUE
EXPECTED_STORAGE_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_STORAGE_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_STORAGE_VALUE
EXPECTED_COMPUTE_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_COMPUTE_LABELS[COMPONENT_LABEL_KEY] = COMPONENT_LABEL_COMPUTE_VALUE
# deployments
EXPECTED_DEPLOYMENTS_LABELS = copy.deepcopy(HCO_COMPONENTS_LABELS_EXPECTED_TEMPLATE)
EXPECTED_DEPLOYMENTS_LABELS.update(
    {
        COMPONENT_LABEL_KEY: COMPONENT_LABEL_DEPLOYMENT_VALUE,
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
    }
)
EXPECTED_DEPLOYMENTS_LABELS_FOR_COMPUTE = copy.deepcopy(EXPECTED_DEPLOYMENTS_LABELS)
EXPECTED_DEPLOYMENTS_LABELS_FOR_COMPUTE[
    COMPONENT_LABEL_KEY
] = COMPONENT_LABEL_COMPUTE_VALUE
EXPECTED_DEPLOYMENTS_LABELS_FOR_IMPORT = copy.deepcopy(EXPECTED_DEPLOYMENTS_LABELS)
EXPECTED_DEPLOYMENTS_LABELS_FOR_IMPORT[
    COMPONENT_LABEL_KEY
] = COMPONENT_LABEL_IMPORT_VALUE
EXPECTED_DEPLOYMENTS_LABELS_FOR_STORAGE = copy.deepcopy(EXPECTED_DEPLOYMENTS_LABELS)
EXPECTED_DEPLOYMENTS_LABELS_FOR_STORAGE[
    COMPONENT_LABEL_KEY
] = COMPONENT_LABEL_STORAGE_VALUE
EXPECTED_DEPLOYMENTS_LABELS_FOR_SCHEDULE = copy.deepcopy(EXPECTED_DEPLOYMENTS_LABELS)
EXPECTED_DEPLOYMENTS_LABELS_FOR_SCHEDULE[
    COMPONENT_LABEL_KEY
] = COMPONENT_LABEL_SCHEDULE_VALUE
EXPECTED_DEPLOYMENTS_LABELS_FOR_NETWORK = copy.deepcopy(EXPECTED_DEPLOYMENTS_LABELS)
EXPECTED_DEPLOYMENTS_LABELS_FOR_NETWORK[
    COMPONENT_LABEL_KEY
] = COMPONENT_LABEL_NETWORK_VALUE
DEPLOYMENTS = {
    CDI_OPERATOR: EXPECTED_DEPLOYMENTS_LABELS_FOR_STORAGE,
    CLUSTER_NETWORK_ADDONS_OPERATOR: EXPECTED_DEPLOYMENTS_LABELS_FOR_NETWORK,
    HCO_OPERATOR: EXPECTED_DEPLOYMENTS_LABELS,
    HCO_WEBHOOK: EXPECTED_DEPLOYMENTS_LABELS,
    HOSTPATH_PROVISIONER_OPERATOR: EXPECTED_DEPLOYMENTS_LABELS_FOR_STORAGE,
    SSP_OPERATOR: EXPECTED_DEPLOYMENTS_LABELS_FOR_SCHEDULE,
    VIRT_OPERATOR: EXPECTED_DEPLOYMENTS_LABELS_FOR_COMPUTE,
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: EXPECTED_DEPLOYMENTS_LABELS,
}
ALL_EXPECTED_LABELS_DICTS = [
    EXPECTED_TEMPLATING_LABELS,
    EXPECTED_SCHEDULE_LABELS,
    EXPECTED_MONITORING_LABELS,
    EXPECTED_NETWORK_LABELS,
    EXPECTED_IMPORT_LABELS,
    EXPECTED_STORAGE_LABELS,
    EXPECTED_COMPUTE_LABELS,
    EXPECTED_DEPLOYMENTS_LABELS,
    EXPECTED_DEPLOYMENTS_LABELS_FOR_COMPUTE,
    EXPECTED_DEPLOYMENTS_LABELS_FOR_IMPORT,
    EXPECTED_DEPLOYMENTS_LABELS_FOR_STORAGE,
    EXPECTED_DEPLOYMENTS_LABELS_FOR_SCHEDULE,
    EXPECTED_DEPLOYMENTS_LABELS_FOR_NETWORK,
]
# HCO components verification dict
EXPECTED_COMPONENT_LABELS_DICT_MAP = {
    ConsoleCLIDownload: {
        VIRTCTL_CLI_DOWNLOADS: {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
    },
    PriorityClass: {
        "kubevirt-cluster-critical": {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
    },
    KubeVirt: {
        "kubevirt-kubevirt-hyperconverged": {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
    },
    CDI: {
        CDI_KUBEVIRT_HYPERCONVERGED: {
            "expected_labels": EXPECTED_STORAGE_LABELS,
        },
    },
    ConfigMap: {
        "grafana-dashboard-kubevirt-top-consumers": {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
            "namespace": "openshift-config-managed",
        },
    },
    NetworkAddonsConfig: {
        "cluster": {
            "expected_labels": EXPECTED_NETWORK_LABELS,
        },
    },
    SSP: {
        SSP_KUBEVIRT_HYPERCONVERGED: {
            "expected_labels": EXPECTED_SCHEDULE_LABELS,
        },
    },
    Service: {
        "kubevirt-hyperconverged-operator-metrics": {
            "expected_labels": EXPECTED_MONITORING_LABELS,
        },
        HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
    },
    ServiceMonitor: {
        "kubevirt-hyperconverged-operator-metrics": {
            "expected_labels": EXPECTED_MONITORING_LABELS,
        },
    },
    PrometheusRule: {
        "kubevirt-hyperconverged-prometheus-rule": {
            "expected_labels": EXPECTED_MONITORING_LABELS,
        },
    },
    ConsoleQuickStart: {
        "creating-virtual-machine": {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
        "upload-boot-source": {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
    },
    Route: {
        HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: {
            "expected_labels": EXPECTED_COMPUTE_LABELS,
        },
    },
}
